### ISSUE TITLE
'How to use' explaination

### ISSUE THREAD

**Issue by wikijm** [gitcolt/am-i-vulnerable-to-meltdown-or-spectre#1]
Hi @gitcolt,

Is it possible to explain how to use it?
For now, I'm able to start the node.js app, nothing more.

Thanks in advance 😄

**Comment by gitcolt** [comment]
Have you navigated to http://localhost:3000 ? Keep in mind this is not a completed app. I just started it last night. The initial commit only shows information for a chrome browser and nothing about your os or cpu.

**Comment by wikijm** [comment]
Thanks for your quick answer.
With your answer, I can display the result of the application.

Everything's working fine, thanks again 😃

**Comment by gitcolt** [comment]
You're welcome
